--!strict
-- Battery uses percentage points; exposure uses seconds of continuous light.
return table.freeze({
	BatteryMax = 100,
	BatteryDrainRate = 100 / 60,
	FlashlightRange = 36,
	BeamAngle = 38,
	Brightness = 3.5,
	ExposureRate = 1,
	ExposureDecayRate = 1.5,
	EffectStartExposure = 1,
	MaxExposure = 6,
	MonsterSlow = 0.08,
	Damage = 4,
	DamageExposure = 2.5,
	DamageCooldown = 4,
	MaxExposureDisorientation = 0.65,
	ResistanceDuration = 5,
	ResistanceEffectMultiplier = 0.1,
	ServerInterval = 0.1,
	AimSendInterval = 0.125,
	AimTimeout = 0.75,
	ToggleCooldown = 0.15,
	MaxMuzzleDistance = 5,
	VisualDistance = 140,
	VisualRayInterval = 1 / 15,
	MaxBlur = 3,
	DisorientationBlur = 2,
	MaxAudioVolume = 0.07,
	-- Built-in assets work without an additional audio upload.
	SwitchSound = "rbxasset://sounds/volume_slider.ogg",
	EmptySound = "rbxasset://sounds/volume_slider.ogg",
	ExposureSound = "rbxasset://sounds/volume_slider.ogg",
})
